### ISSUE TITLE
(gcloud.config.set) argument VALUE: Must be specified.

### ISSUE THREAD

**Issue by GrubbyDungles** [zenjabba/f1-control#5]
SPins up first instance now and runs through rclone config successfully. 

## First error.
/opt/f1-control/spinup.sh first-instance us-west2-a
basename: extra operand ‘https://cloudresourcemanager.googleapis.com/v1/projects/vm-rclone-test-166201’
Try 'basename --help' for more information.
ERROR: (gcloud.config.set) argument VALUE: Must be specified.

## After 'q' rclone config
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
no crontab for myusername
Access this instance with the command # sudo -s gcloud beta compute ssh first-instance --zone us-west2-a --project=

**Comment by zenjabba** [comment]
because it was uable to get the value for project (basename failed). Interesting

**Comment by zenjabba** [comment]
needed to quote the variable for some reason.

https://github.com/zenjabba/f1-control/commit/0a2a2a042e32208b3b0372f11b0a2abef65f9ac9#diff-f3f03edcedf06aa01f18e22cc776eb00

**Comment by zenjabba** [comment]
Also, it should create crontab for root
