### ISSUE TITLE
HTTPError 403: Access Not Configured.

### ISSUE THREAD

**Issue by GrubbyDungles** [zenjabba/f1-control#6]
/opt/f1-control/spinup.sh first-instance us-west2-a
```
Updated property [core/project].
ERROR: (gcloud.beta.compute.instances.create) HTTPError 403: Access Not Configured. Compute Engine API has not been
 used in project 1000078063258 before or it is disabled. Enable it by visiting https://console.developers.google.co
m/apis/api/compute.googleapis.com/overview?project=1000078063258 then retry. If you enabled this API recently, wait
 a few minutes for the action to propagate to our systems and retry.
 failed. Fix the error and start again with /opt/f1-control/spinup.sh first-instance us-west2-a
```

**Comment by zenjabba** [comment]
That's because you have not enabled it. follow the URL and enable it :)

**Comment by GrubbyDungles** [comment]
Copy paste error I thought. But I did notice it's selected a different project id when running the second time and got the same error.
`sudo gcloud config set project PROJECT_ID`
And run again gives same error.
Following link I notice project ID is the incorrect one still
But sticks to same project ID as before.
Create 0 auth for correct project ID
Set project ID and rerun `sudo f1-control/configure-gce.sh email@`
Correct project selected but still error and following  'Enable it by visiting... leads to incorrect project ID.

Start again with fresh instance.
now works but...
`/opt/f1-control/spinup.sh first-instance us-west2-a`

```
ssh: connect to host 35.236.35.88 port 22: Connection refused
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```
**host IP is vm instance created in wrong project**

```
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
no crontab for <myusername>
Access this instance with the command # sudo -s gcloud beta compute ssh first-instance --zone us-west2-a --project=
taskerapi
```

**taskerapi is wrong project**

**Comment by zenjabba** [comment]
fixed up by getting the correct project.
